AllCops:
  Exclude:
    - bin/*
    - vendor/bundle/**/*
LineLength:
  Max: 250
HashSyntax:
  Enabled: False
FileName:
  Enabled: False
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/AsciiComments:
  Enabled: false
