AllCops:
  Exclude:
    - config/software/cacerts.rb
    - config/software/openssl.rb
    - config/software/nodejs.rb
    - config/software/nokogiri.rb
    - config/software/bzip2.rb
    - bin/*
    - vendor/bundle/**/*
LineLength:
  Max: 250
HashSyntax:
  Enabled: False
FileName:
  Enabled: False
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/AsciiComments:
  Enabled: false
